"""Agent state definition for the Clinical Code Intelligence Agent.

The state flows through the LangGraph state machine. Each node reads from
and writes to this shared TypedDict. LangGraph handles merging updates
automatically — nodes return only the keys they modify.
"""

from typing import TypedDict


class AgentState(TypedDict, total=False):
    """Shared state passed between all graph nodes.

    Attributes:
        query: The user's original input (code or natural language question).
        query_type: Classified intent — 'code_lookup', 'semantic_search',
            'hierarchy', 'drg_explain', or 'general'.
        tool_results: Raw results returned by the selected tool(s).
        synthesis: The final human-readable explanation generated by the LLM.
        citations: Source references for claims in the synthesis.
        confidence: How confident the agent is in its answer (0.0-1.0).
        messages: Trace of actions taken (for observability/debugging).
        error: Error message if something failed.
    """

    query: str
    query_type: str
    tool_results: list[dict[str, object]]
    synthesis: str
    citations: list[str]
    confidence: float
    messages: list[str]
    error: str
